---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: quarkus-app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/raffamendes/argocd-demo.git
